HOLOGRAM_LINE_1 = "&eEnjoy your stay"
HOLOGRAM_LINE_2 = "&bHit a NPC to join a game!"
HOLOGRAM_LINE_3 = "&eThere are &a%s &eplayers on the network"
HOLOGRAM_LINE_4 = "&eYou are in the hub"
HOLOGRAM_LINE_5 = "&ahttps://web.clovercube.net"
HOLOGRAM_LINE_6 = "&9CloverCube &cBETA"
HOLOGRAM_LINE_7 = "&bplay.clovercube.net"
MARKETPLACE_NPC_TAG_HEADER = "&l&cMarketplace"
MARKETPLACE_NPC_TAG_FOOTER = "&eClick to explore"
CLICK_TO_PLAY_NPC_TAG_FOOTER = "&7Click to join game"
NEW_NPC_TAG_HEADER = "&eNEW GAME"
COMING_SOON_NPC_TAG_HEADER = "&cCOMING SOON"
TITLE_JOIN = "&l&cClover&9Cube"
SUBTITLE_JOIN = "&r&ehttps://web.clovercube.net"
ITEM_GAMES = "&9&lGAMES"
ITEM_COSMETIC = "&a&lGADGETS"
ITEM_FIREWORK = "&b&lFIREWORKS"
FORM_OPTION_ACTIVATE = "&r&fClick to select"
COSMETIC_FLY = "&l&aFLY"
COSMETIC_FLY_ACTIVATED = "&aFly activated"