HOLOGRAM_LINE_1 = "&eEnjoy your stay"
HOLOGRAM_LINE_2 = "&bHit a NPC to join a game!"
HOLOGRAM_LINE_3 = "&eThere are &a%s &eplayers on the network"
HOLOGRAM_LINE_4 = "&eYou are in the hub"
HOLOGRAM_LINE_5 = "&aweb.clovercube.net"
HOLOGRAM_LINE_6 = "&9CloverCube &cBETA"
HOLOGRAM_LINE_7 = "&bplay.clovercube.net"
MARKETPLACE_NPC_TAG_HEADER = "&l&cMarketplace"
MARKETPLACE_NPC_TAG_FOOTER = "&eClick to explore"