game-description = "&eEach player will have 5 lives, when your life counter reaches 0, you will be eliminated, the last player standing or the one with the most points will win!"
my-lives = "&bLives left: &f%s"
my-points = "&bMy points: &f%s"
lost-life = "&a> &fYou lost a life"
got-point = "&a> &fYou got a point"
best-scores = "&c&lBEST SCORES"
player-eliminated = "%s &ewas eliminated!"