game-description = "&eCada jugador tendrá 5 vidas, cuando tu contador de vidas llegue a 0, serás eliminado, ¡ganará el último jugador en pie o el que tenga más puntos!"
my-lives = "&bVidas restantes: &f%s"
my-points = "&bMis puntos: &f%s"
lost-life = "&a> &fPerdiste una vida"
got-point = "&a> &fObtuviste un punto"
best-scores = "&c&lMEJORES PUNTAJES"
player-eliminated = "&e¡%s &e fue eliminado!"