welcome-header = "&eWelcome to &c%s&e!"
welcome-footer = "&eYou are playing on game:&f %s"
player-join = "&7%s &ejoin the game (%s/%s)"
player-left = "&7%s &eleft the game (%s/%s)"
seconds-to-start = "&eThe game will start in %s seconds..."
exit-citizen-header = "&l&bBack to hub"
exit-citizen-footer = "&eClick here"
stats-citizen-header = "&l&bYour stats"
stats-citizen-soon = "&eComing soon"
already-vote = "&cYou have already voted for a map."
vote-success = "&eYou have voted for the map:&f %s"
closed-voting = "&cThe time to vote is over."
winner-map-header = "&bMap %s"
winner-map-footer = "&eBy %s"
generating-map = "&bGenerating map..."
vote-citizen-header = "&l&bVote for map"
vote-citizen-footer = "&eClick here"
vote-map-title = "VOTE FOR MAP"
vote-map-description = "Vote for the map you would like to play on this game"
map-credits = "The map %s built by %s"
vote = "&l&2VOTE"
next-map = "&l&cNEXT MAP"
preferences-citizen-header = "&l&bMatch preferences"
preferences-citizen-footer = "&eClick here"
preferences-title = "MATCH PREFERENCES"
preferences-description = "Set preferences for your match"
not-enough-players = "&4Not enough players to start the game"
already-started = "&6The game has already started!"
forced-start = "&6The player %s forced the start of the game. Starting in 15 seconds!"
game-over-header = "&l&fGAME OVER"
you-died-footer = "&8You died"
no-winners-footer = "&8There are no winners"
alive = "&bAlive: &7%s"
time-left = "&bTime left: &f%s"
won-game = "&aCongratulations. %s &awon the game!"
seconds-to-end = "&eThe game will end in %s seconds..."
my-kills = "&bKills: &7%s"
go-back = "&cGo back"
player-died = "%s &edied"
player-died-cause-fire = "%s &eburned to death"
player-died-cause-fall = "%s &efell to the ground"
player-died-cause-drowning = "%s &edrowned"
player-died-cause-explosion = "%s &eexploded"
player-died-cause-void = "%s &efell into the void"
player-died-killed-by-player = "%s &ewas killed by %s"
player-died-cause-fire-killed-by-player = "%s &ewas set fire by %s"
player-died-cause-fall-killed-by-player = "%s &efell to the ground while escaping from %s"
player-died-cause-drowning-killed-by-player = "%s &e was drowned by %s"
player-died-cause-explosion-killed-by-player = "%s &eexploded thanks to %s"
player-died-cause-void-killed-by-player = "%s &efell to the void while escaping from %s"
you-assisted = "&eYou assisted to kill %s"
