welcome-header = "&eBienvenido a &c%s&e!"
welcome-footer = "&eEstás jugando en la partida:&f %s"
player-join = "&a> &f%s &7entro al juego &a(&f%s&a/&f%s&a)"
player-left = "&a> &f%s &7salió del juego &a(&f%s&a/&f%s&a)"
seconds-to-start = "&eLa partida comenzará en %s segundos..."
exit-citizen-header = "&l&bRegresar"
exit-citizen-footer = "&eClic aquí"
stats-citizen-header = "&l&bTus estadísticas"
stats-citizen-soon = "&eMuy pronto"
already-vote = "&cYa has votado por un mapa."
vote-success = "&eHas votado por el mapa:&f %s"
closed-voting = "&cEl tiempo para votar ha finalizado."
winner-map-header = "&bMapa %s"
winner-map-footer = "&ePor %s"
generating-map = "&bGenerando mapa..."
vote-citizen-header = "&l&bVota por el mapa"
vote-citizen-footer = "&eClic aquí"
vote-map-title = "VOTA POR EL MAPA"
vote-map-description = "Vota por el mapa que te gustaría jugar en esta partida"
map-credits = "El mapa %s fue construido por %s"
vote = "&l&2VOTAR"
next-map = "&l&cPROXIMO MAPA"
preferences-citizen-header = "&l&bPreferencias de partida"
preferences-citizen-footer = "&eClic aquí"
preferences-title = "PREFERENCIAS DE PARTIDA"
preferences-description = "Establecer preferencias para su partida"
not-enough-players = "&4No hay suficientes jugadores para iniciar la partida"
already-started = "&6¡El juego ya ha comenzado!"
forced-start = "&6El jugador %s forzó el inicio de la partida. ¡Empezando en 15 segundos!"
game-over-header = "&l&fJUEGO TERMINADO"
you-died-footer = "&8Moriste"
no-winners-footer = "&8No hay ganadores"
alive = "&bVivos: &f%s"
time-left = "&bTiempo restante: &f%s"
won-game = "&aFelicidades. &a¡%s &aganó el juego!"
seconds-to-end = "&eEl juego terminará en %s segundos..."
my-kills = "&bAsesinatos: &f%s"
go-back = "&cRegresar"
player-died = "%s &emurió"
player-died-cause-fire = "%s &ese quemó hasta morir"
player-died-cause-fall = "%s &ecayó al suelo"
player-died-cause-drowning = "%s &ese ahogó"
player-died-cause-explosion = "%s &eexplotó"
player-died-cause-void = "%s &ecayó al vacio"
player-died-killed-by-player = "%s &efue asesinado por %s"
player-died-cause-fire-killed-by-player = "%s &efue incendiado por %s"
player-died-cause-fall-killed-by-player = "%s &ecayó al suelo mientras escapaba de %s"
player-died-cause-drowning-killed-by-player = "%s &e fue ahogado por %s"
player-died-cause-explosion-killed-by-player = "%s &eexplotó gracias a %s"
player-died-cause-void-killed-by-player = "%s &ecayó al vacio mientras escapaba de %s"
you-assisted = "&eAyudaste a matar a %s"