game-description = "&ePlayers spawn on islands where there are barrels with loot, with which you have to equip yourself and fight against other players, the last player standing will win!"
refill-time = "&bRefilling in: &f%s"
refilling = "&eThe barrels are refilling"