game-description = "&e¡Los jugadores aparecen en islas donde hay barriles con botín, con los que debes equiparte y luchar contra otros jugadores, el último jugador en pie ganará.!"
refill-time = "&bRellenando en: &f%s"
refilling = "&eLos barriles se están rellenando"