playing-in = "&l&eYOU ARE PLAYING ON &cCLOVER&9CUBE &eNETWORK"
prefix-1 = "&l&cCLOVER&9CUBE &r&7| &r"
void = ""
VPN_BLOCKED = "Don't use VPN to play on this server"
NETWORK_FULL = "&cNetwork full..."
PLAYER_IS_NOT_ONLINE = "&c%s is not online..."
SERVER_EQUALS = "&cYou are already on server %s"
PLAYER_TELEPORTED_PLAYER = "&aTeletransporting &f%s &ato &7%s server..."
INVALID_RANK = "&cThe range %s is invalid..."
PLAYER_NOT_EXIST = "&cThis player does not exist..."
PLAYER_NOT_ONLINE = "&cThe player %s is not online..."
OPTION_NOT_EXIST = "&cThe option %s does not exist..."
MODE_NOT_EXIST = "&cMode %s does not exist..."
RANK_PLAYER_EQUALS = "&cThe player %s already has the rank %s"
GIVE_RANK = "&aCongratulations player %s!&aYou have been ranked %s&7Enjoy it!"
REPORT_SENDING = "&aYour report has been successfully sent to the administration!"
ID_SANCTION_NOT_EXIST = "&c%s not found..."
BANNED = "&cYou have been banned..."
BANNED_BROADCAST = "banned"
MUTED = "&cHas been muted"
MUTED_BROADCAST = "muted"
MUTE_OPTION_NOT_AVAILABLE = "&c%s is not a reason for mute..."
KICKED = "&cYou have been kicked out..."
KICKED_BROADCAST = "kicked out"
KICK_OPTION_NOT_AVAILABLE = "&c%s is not an expulsion reason..."
PERM = "PERMANENTLY"
TEMP = "TEMPORARILY"
EXPIRE = "&7Expires in %s days %s hours with %s minutes"
REASON = "&eReason: &r&e%s"
CHEATING = "Use of illegal advantages"
SPAM = "Sending promotional messages to own or third party network"
TEAM = "Teaming up with another player in a mode"
NAME = "Use of an inappropriate name"
SKIN = "Use of inappropriate or obscene skin"
BUG = "Taking advantage of server bugs"
ADVERTISING = "Warning"
TOXIC = "Inappropriate behavior"
ALL = "Banned"
SANCTION_BROADCAST = "&l&c%s&r&7(%s) was %s %s %s for (Reason: &c&l%s&r&7)"