playing-in = "&l&eESTAS JUGANDO EN &cCLOVER&9CUBE &eNETWORK"
prefix-1 = "&l&cCLOVER&9CUBE &r&7| &r"
void = ""
CONNECTING = "&aConectando..."
VPN_BLOCKED = "No uses VPN para jugar en esté servidor"
NETWORK_FULL = "&cNetwork llena..."
PLAYER_IS_NOT_ONLINE = "&c%s no está en linea..."
SERVER_EQUALS = "&cYa estas en el servidor %s"
PLAYER_TELEPORTED_PLAYER = "&aTeletransportando a &f%s &aal servidor &7%s"
INVALID_RANK = "&cEl rango %s es invalido..."
PLAYER_NOT_EXIST = "&cEste jugador no existe..."
PLAYER_NOT_ONLINE = "&cEl jugador %s no está en linea..."
OPTION_NOT_EXIST = "&cLa opcion %s no existe..."
MODE_NOT_EXIST = "&cEl modo %s no existe..."
RANK_PLAYER_EQUALS = "&cEl jugador %s ya tiene el rango %s"
GIVE_RANK = "&a¡Felicidades jugador %s!\n&aSe te ha colocado el rango %s\n&7¡Disfrutálo!"
REPORT_SENDING = "&a¡Tu reporte se ha enviado con exito a la administración!"
ID_SANCTION_NOT_EXIST = "&c%s no encontrado..."
BANNED = "&cHas sido baneado"
BANNED_BROADCAST = "baneado"
MUTED = "&cHas sido muteado"
MUTED_BROADCAST = "muteado"
MUTE_OPTION_NOT_AVAILABLE = "&c%s no es una razon de muteo..."
KICKED = "&cHas sido expulsado"
KICKED_BROADCAST = "expulsado"
KICK_OPTION_NOT_AVAILABLE = "&c%s no es una razon de expulsion..."
PERM = "PERMANENTEMENTE"
TEMP = "TEMPORALMENTE"
EXPIRE = "&7Expira en %s dias %s horas con %s minutos"
REASON = "&eRazon: &r&e%s"
CHEATING = "Uso de ventajas ilegales"
SPAM = "Enviar mensajes de promoción a una red propia o de terceros"
TEAM = "Hacer equipo con otro jugador en una modalidad"
NAME = "Uso de nombre inapropiado"
SKIN = "Uso de skin inapropiado u obsceno"
BUG = "Aprovecharse de fallos del servidor"
ADVERTISING = "Advertencia"
TOXIC = "Comportamiento inadecuado"
ALL = "Vetado"
SANCTION_BROADCAST = "&l&c%s&r&7(%s) fue %s %s por (Razon: &c&l%s&r&7)"
RANK = "Rango"
NOT_PERMISSION = "&c&lNo&r&c tienes permisos para usar esta funcion\n&a¡Compra un rango en &ehttps://shop.clovercube.net&a!"
LANGUAGE = "Español"