playing-in = "&l&eESTAS JUGANDO EN &cCLOVER&9CUBE &eNETWORK"
prefix-1 = "&l&cCLOVER&9CUBE &r&7| &r"
void = ""
VPN_BLOCKED = "No uses VPN para jugar en esté servidor"
NETWORK_FULL = "Network llena..."
PLAYER_IS_NOT_ONLINE = "&c%s no está en linea..."
SERVER_EQUALS = "&cYa estas en el servidor %s"
PLAYER_TELEPORTED_PLAYER = "&aTeletransportando a &f%s &aal servidor &7%s"
INVALID_RANK = "&cEl rango %s es invalido..."
PLAYER_NOT_EXIST = "&cEste jugador no existe..."
PLAYER_NOT_ONLINE = "&cEl jugador %s no está en linea..."
RANK_PLAYER_EQUALS = "&cEl jugador %s ya tiene el rango %s"
GIVE_RANK = "&a¡Felicidades jugador %s!\n&aSe te ha colocado el rango %s\n&7¡Disfrutálo!"
REPORT_SENDING = "&a¡Tu reporte se ha enviado con exito a la administración!"